### ISSUE TITLE
fontaine-set-preset: Cannot use this in a terminal emulator; try the Emacs GUI

### ISSUE THREAD

**Issue by jgarte** [protesilaos/fontaine#12] opened 2024-12-28 03:54 UTC
Hi,

I get this message when I open Emacs in my terminal with `emacs -nw` and these fonts enabled.

> fontaine-set-preset: Cannot use this in a terminal emulator; try the Emacs GUI

https://github.com/protesilaos/fontaine/blob/e689b0c55e872e64bff47d157cad58854ff0e564/fontaine.el#L479

Would it be possible to support terminal usage for these fonts?

**Comment by protesilaos** [comment] 2024-12-28 07:50
> From: Jorge Gomez ***@***.***>
> Date: Fri, 27 Dec 2024 19:55:03 -0800
>
> Hi,
>
> I get this message when I open Emacs in my terminal with `emacs -nw` and these fonts enabled.
>
>> fontaine-set-preset: Cannot use this in a terminal emulator; try the Emacs GUI
>
> Would it be possible to support terminal usage for these fonts?

The problem is that Emacs cannot set fonts in the terminal: it uses what
the terminal emulator defines.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jgarte** [comment] 2024-12-28 14:38
TIL, thanks for the info.

> The problem is that Emacs cannot set fonts in the terminal: it uses what
the terminal emulator defines.

Is the issue then that this error message should be less noisy?

I thought there was something wrong with my Emacs when that user-error was raised:

https://github.com/protesilaos/fontaine/blob/e689b0c55e872e64bff47d157cad58854ff0e564/fontaine.el#L480

What if we did this instead?

```
(if (and (not (daemonp)) (not window-system))
  (display warning "Cannot use this in a terminal emulator; try the Emacs GUI")
```

The default log level is `:warning:` as described here:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Warning-Basics.html

WDYT

**Comment by protesilaos** [comment] 2024-12-29 07:19
Yes, this is better. I just merged your PR. Thank you!

**Closed by protesilaos** 2024-12-29 07:18 UTC
